- name: ensure minio dir exist
  file:
    path: '{{ minio_root_dir }}'
    state: directory

- name: copy minio docker-compose file
  template:
    src: docker-compose.yaml.j2
    dest: '{{ minio_root_dir }}/docker-compose.yaml'

- name: ensure minio data dir exist
  file:
    path: '{{ minio_root_dir }}/data'
    state: directory
    mode: 0777

- name: ensure minio config dir exist
  file:
    path: '{{ minio_root_dir }}/config'
    state: directory
    mode: 0777

#- name: cp docker-compose
#  copy:
#    src: /etc/ansible/tools/docker-compose
#    dest: /usr/local/bin/

#- name: chmod docker-compose
#  shell: chmod +x /usr/local/bin/docker-compose

- name: start up minio
  shell: docker compose up -d
  args:
    chdir: '{{ minio_root_dir }}'

- name: wait minio api ready
  wait_for:
    port: 9000
    timeout: 60

- name: wait minio console ready
  wait_for:
    port: 9001
    timeout: 60