- name: change sys conf
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - "fs.file-max = 2097152"
    - "vm.drop_caches = 1"
    - "vm.zone_reclaim_mode = 0"
    - "vm.dirty_background_ratio = 50"
    - "vm.dirty_ratio = 50"
    - "vm.page-cluster = 3"
    - "vm.dirty_writeback_centisecs = 360000"
    - "vm.swappiness = 1"
    - "vm.max_map_count = 655360"
    - "vm.overcommit_memory=1"

- name: change /etc/security/limits.conf
  lineinfile:
    path: /etc/security/limits.conf
    regexp: ".* memlock .*"
    line: "* - memlock      unlimited"
    state: present

- name: Enable /etc/profile
  shell: /bin/bash /etc/profile
- name: create group for rocketmq
  group:
    name: '{{ rocketmq_group }}'
    state: present

- name: create user for rocketmq
  user:
    name: '{{ rocketmq_user }}'
    group: '{{ rocketmq_group }}'
    state: present