- name: 服务器初始化
  ignore_errors: false
  gather_facts: false
  hosts:
    - k8s_master_init
    - k8s_master_join
    - k8s_worker
  roles:
    - disable-firewalld
    - change-hostname
    - change-sysconf
    - install-apt-source
    - install-ntp-client
    - install-docker
    - install-cri-dockerd


 ##安装kubernetes
- name: install kubelet kubeadm kubectl
  hosts:
    - k8s_worker
    - k8s_master_join
    - k8s_master_init
  gather_facts: true
  ignore_errors: false
  pre_tasks:
    - name: 安装kubeadm kubectl kubelet
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        update_cache: true
        state: present
    - name: 刷新kubeadm
      copy:
        src: /etc/ansible/tools/kubeadm
        dest: "/usr/bin/kubeadm"
        mode: 0777
  roles:
    #多master节点需要安装keepalived，放开下面的"install-keepalived"
    #- { role: install-keepalived, when: ansible_default_ipv4.address in (k8s_master_init) or ansible_default_ipv4.address in (k8s_master_join) }
    - { role: k8s-master-init-single, when: ansible_default_ipv4.address in (k8s_master_init) }
    - { role: k8s-node-join, when: ansible_default_ipv4.address in (k8s_master_join) or ansible_default_ipv4.address in (k8s_worker) }
    - { role: install-etcd-backup-cron, when: ansible_default_ipv4.address in (k8s_master_init) }
    - { role: k8s-install-component, when: ansible_default_ipv4.address in (k8s_master_init) }
  post_tasks:
    - name: 修改roles-label
      shell: "kubectl label --overwrite node {{ hostvars[item].host_name }} {{ hostvars[item].label }}"
      loop: "{{ query('inventory_hostnames', 'k8s-node') }}"