- name: 服务器初始化
  ignore_errors: false
  gather_facts: false
  hosts:
    - zookeeper
  roles:
    - disable-firewalld
    - change-hostname
    - change-sysconf
    - install-dns-client
    - install-apt-source
    - install-ntp-client
    - install-docker

- name: install zk cluster
  hosts:
    - zookeeper
  gather_facts: false
  roles:
    - install-zk
    - install-zk-exporter