- name: 服务器初始化
  ignore_errors: false
  gather_facts: false
  hosts:
    - nexus
  roles:
    - disable-firewalld
    - change-hostname
    - change-sysconf
    - install-apt-source
    - install-ntp-client
    - install-docker
- name: install nexus
  hosts:
    - nexus
  gather_facts: false
  ignore_errors: false
  roles:
    - install-nexus