- name: 服务器初始化
  ignore_errors: false
  gather_facts: false
  hosts:
    - gitlab
  roles:
    - disable-firewalld
    - change-hostname
    - change-sysconf
    - install-apt-source
    - install-ntp-client
    - install-docker

- name: install gitlab
  hosts:
    - gitlab
  gather_facts: false
  ignore_errors: false
  roles:
    - install-git