- name: 服务器初始化
  ignore_errors: false
  gather_facts: false
  hosts:
    - minio
  roles:
    - disable-firewalld
    - change-hostname
    - change-sysconf
    - install-apt-source
    - install-ntp-client
    - install-docker
- name: install minio
  hosts: minio
  gather_facts: false
  roles:
    - install-minio