- name: 服务器初始化
  ignore_errors: true
  gather_facts: true
  hosts:
#    - dns_infra
    - ntp_infra
  roles:
#    - disable-firewalld
#    - change-hostname
#    - change-sysconf
#    - install-dns-client
#    - install-apt-source
    - install-ntp-client

 ##安装kafka集群
#- name: install kafka cluster
#  hosts:
#    - ntp_infra
#    - dns_infra
#  gather_facts: true
#  ignore_errors: false
#  vars_files:
#    - "{{inventory_dir}}/group_vars/docker.yaml"
#  roles:
#    - install-docker