- name: 服务器初始化
  ignore_errors: false
  gather_facts: false
  hosts:
    - k8s_master_init
    - k8s_master_join
    - k8s_worker
  roles:
    - disable-firewalld
    - change-hostname
    - change-sysconf
    - install-apt-source
    - install-ntp-client
    - install-containerd


 ##安装kubernetes
- name: install kubelet kubeadm kubectl
  hosts:
    - k8s_worker
    - k8s_master_join
    - k8s_master_init
  gather_facts: true
  ignore_errors: false
  pre_tasks:
    - name: 安装kubeadm kubectl kubelet
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        update_cache: true
        state: present
    - name: 刷新kubeadm
      copy:
        src: /etc/ansible/tools/kubeadm
        dest: "/usr/bin/kubeadm"
        mode: 0777
    - name: 设置crictl配置文件
      shell: |
        cat > /etc/crictl.yaml << EOF
        runtime-endpoint: unix:///run/containerd/containerd.sock
        image-endpoint: unix:///run/containerd/containerd.sock
        timeout: 10
        debug: false
        EOF
    - name: specify node ip
      lineinfile:
        path: /etc/default/kubelet
        regexp: "^KUBELET_EXTRA_ARGS"
        line: "KUBELET_EXTRA_ARGS=--node-ip={{ ansible_ssh_host }} --root-dir={{ kubelet_data_dir }}"
        state: present
    - name: 创建 /data01/var/log/pods目录
      file:
        path: /data01/var/log/pods
        state: directory
        mode: 0755
    - name: 确保 /var/log/pods 目录不存在
      file:
        path: /var/log/pods
        state: absent
    - name:  创建链接 /var/log/pods
      file:
        src: /data01/var/log/pods
        dest: /var/log/pods
        state: link
  roles:
    #多master节点需要安装keepalived，放开下面的"install-keepalived"
    - { role: install-keepalived, when: ansible_default_ipv4.address in (k8s_master_init) or ansible_default_ipv4.address in (k8s_master_join) }
    - { role: k8s-master-init-containerd-single, when: ansible_default_ipv4.address in (k8s_master_init) }
    - { role: k8s-node-containerd-join, when: ansible_default_ipv4.address in (k8s_master_join) or ansible_default_ipv4.address in (k8s_worker) }
    - { role: install-etcd-backup-cron, when: ansible_default_ipv4.address in (k8s_master_init) }
    - { role: k8s-install-component, when: ansible_default_ipv4.address in (k8s_master_init) }
 ##打label
- name: change k8s node label
  hosts:
    - k8s_master_init
  gather_facts: false
  tasks:
    - name: 修改k8s master init roles-label
      shell: "kubectl label --overwrite node {{ hostvars[item].host_name }} {{ hostvars[item].label }}"
      loop: "{{ query('inventory_hostnames', 'k8s_master_init') }}"
    - name: 修改k8s master join roles-label
      shell: "kubectl label --overwrite node {{ hostvars[item].host_name }} {{ hostvars[item].label }}"
      loop: "{{ query('inventory_hostnames', 'k8s_master_join') }}"