- name: create zookeeper-ui root dir
  file:
    path: '{{ zookeeper_ui_dir }}'
    state: directory

- name: cp docker-compose
  template:
    src: docker-compose.yml.j2
    dest: '{{ zookeeper_ui_dir }}/docker-compose.yml'

- name: start zookeeper-ui
  shell: /usr/local/bin/docker-compose up -d
  args:
   chdir: "{{ zookeeper_ui_dir }}"

- name: wait zookeeper-ui ready
  wait_for:
    port: 9090
    delay: 10
    timeout: 120
    msg: 'Timeout waiting for zookeeper-ui respond'
