redis_data_dir: '/data01/redis'
redis_password: 'password'
#16G大小的3/4
redis_maxmemory: "{{ 48|int * 1024|int * 1024|int * 1024|int }}"
redis_maxmemory_policy: allkeys-lru
# filebeat config
filebeat_config: "filebeat-redis.yml.j2"