- name: modify sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - "vm.overcommit_memory = 1"

- name: sysctl enable
  shell: sysctl -p /etc/sysctl.conf

- name: create root dir
  file:
    path: '{{ zk_root_dir }}'
    state: directory
    mode: 0777

- name: check if zk exists
  stat:
    path: '{{ zk_root_dir }}/docker-compose.yml'
  register: zk_compose_file

- name: stop existed kafka container
  shell: docker compose down
  when: zk_compose_file.stat.exists == true
  args:
    chdir: "{{ zk_root_dir }}"

- name: install with docker compose
  template: 
    src: docker-compose.yml.j2
    dest: "{{ zk_root_dir }}/docker-compose.yml"

- name: create container volums
#  command: mkdir -p {{ zk_root_dir }}/zookeeper/conf {{ zk_root_dir }}/zookeeper/data {{ zk_root_dir }}/zookeeper/datalog
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ zk_root_dir }}/zookeeper/conf"
    - "{{ zk_root_dir }}/zookeeper/data"
    - "{{ zk_root_dir }}/zookeeper/datalog"

#- name: chmod dir
#  command: chmod -R a+rwx {{ zk_root_dir }}/zookeeper/conf {{ zk_root_dir }}/zookeeper/data {{ zk_root_dir }}/zookeeper/datalog

- name: shutdown zookeeper
  command: docker compose -f {{ zk_root_dir }}/docker-compose.yml down

- name: start up zookeeper
  command: docker compose -f {{ zk_root_dir }}/docker-compose.yml up -d

- name: wait zookeeper ready
  wait_for:
    port: 2181
    timeout: 180
    msg: 'Timeout waiting for zookeeper respond'

- name: modify autopurge.snapRetainCount
  shell: sed -i "s;autopurge.snapRetainCount=3$;autopurge.snapRetainCount=30;g" ./zookeeper/conf/zoo.cfg
  args:
    chdir: "{{ zk_root_dir }}"

- name: modify autopurge.purgeInterval
  shell: sed -i "s;autopurge.purgeInterval=0$;autopurge.purgeInterval=72;g" ./zookeeper/conf/zoo.cfg
  args:
    chdir: "{{ zk_root_dir }}"

- name: 添加暴露zk指标的参数4lw.commands.whitelist=*
  lineinfile:
    path: "{{ zk_root_dir }}/zookeeper/conf/zoo.cfg"
    line: "4lw.commands.whitelist=*"
    state: present

- name: shutdown zookeeper
  command: docker compose -f {{ zk_root_dir }}/docker-compose.yml down

- name: start up zookeeper
  command: docker compose -f {{ zk_root_dir }}/docker-compose.yml up -d

- name: wait zookeeper ready
  wait_for:
    port: 2181
    timeout: 180
    msg: 'Timeout waiting for zookeeper respond'