---
apiVersion: v1
kind: Secret
metadata:
  name: adc-admin
  namespace: adc
  annotations:
    kubernetes.io/service-account.name: "adc-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: fdc-admin
  namespace: fdc
  annotations:
    kubernetes.io/service-account.name: "fdc-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: noticeservice-admin
  namespace: noticeservice
  annotations:
    kubernetes.io/service-account.name: "noticeservice-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: report-admin
  namespace: report
  annotations:
    kubernetes.io/service-account.name: "report-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: yms-admin
  namespace: yms
  annotations:
    kubernetes.io/service-account.name: "yms-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: oee-admin
  namespace: oee
  annotations:
    kubernetes.io/service-account.name: "oee-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: dms-admin
  namespace: dms
  annotations:
    kubernetes.io/service-account.name: "dms-admin"
type: kubernetes.io/service-account-token
---