kafka_root_dir: '/data01/kafka'
kafka_heap_opts: '-Xmx32G -Xms32G'
kafka_hosts_str: '{{ groups["kafka_yes"] | map("regex_replace", "^(.*)$","\1:9092") | list | join(",") }}'
# nginx需要引用，不能修改为ansible_play_hosts_all
kafka_hosts_arr: '{{ groups["kafka_yes"] | map("regex_replace", "^(.*)$","\1:9092") | list | to_json }}'

zk_root_dir: '/data01/zookeeper'
ZK_SERVER_HEAP: 8192
ZK_CLIENT_HEAP: 4096
zk_hosts_str: '{{ groups["kafka_yes"] | map("regex_replace", "^(.*)$","\1:2181") | join(",") }}'