apiVersion: v1
kind: ResourceQuota #需要添加--enable-admission-plugins=ResourceQuota
metadata:
  name: default-resource-quota
spec:
  hard:
    pods: "2000" #集群总数 2000
    services: "2000"
# jd除了kube-system所有应用都有request和limite
#---
#apiVersion: v1
#kind: LimitRange
#metadata:
#  name: default-limit-range
#spec:
#  limits:
#    - default:
#        memory: 4Gi
#        cpu: "1"
#      defaultRequest:
#        memory: 100Mi
#        cpu: "0.02"
#      max:
#        memory: 64Gi
#        cpu: "32"
#      min:
#        memory: 100Mi
#        cpu: "0.01"
#      type: Pod