apiVersion: v1
kind: ResourceQuota #需要添加--enable-admission-plugins=ResourceQuota
metadata:
  name: default-resource-quota
spec:
  hard:
    pods: "2000" #集群总数 2000
    services: "2000"
# jd除了kube-system所有应用都有request和limite
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: default
spec:
  limits:
    - default:
        memory: 2Gi
        cpu: "0.5"
      defaultRequest:
        memory: 100Mi
        cpu: "0.02"
      max:
        memory: 4Gi
        cpu: "1"
      min:
        memory: 10Mi
        cpu: "0.001"
      type: Container