---
apiVersion: v1
kind: Secret
metadata:
  name: ams-gray-admin
  namespace: ams-gray
  annotations:
    kubernetes.io/service-account.name: "ams-gray-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: ams-admin 
  namespace: ams
  annotations:
    kubernetes.io/service-account.name: "ams-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: apc-admin
  namespace: apc
  annotations:
    kubernetes.io/service-account.name: "apc-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: eap-admin
  namespace: eap
  annotations:
    kubernetes.io/service-account.name: "eap-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: mes-admin
  namespace: mes
  annotations:
    kubernetes.io/service-account.name: "mes-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: mes-gray-admin
  namespace: mes-gray
  annotations:
    kubernetes.io/service-account.name: "mes-gray-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: notice-gray-admin
  namespace: notice-gray
  annotations:
    kubernetes.io/service-account.name: "notice-gray-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: notice-admin
  namespace: notice
  annotations:
    kubernetes.io/service-account.name: "notice-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: rms-admin 
  namespace: rms 
  annotations:
    kubernetes.io/service-account.name: "rms-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: rtd-admin 
  namespace: rtd 
  annotations:
    kubernetes.io/service-account.name: "rtd-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: sdr-admin 
  namespace: sdr 
  annotations:
    kubernetes.io/service-account.name: "sdr-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: skywalking-admin 
  namespace: skywalking 
  annotations:
    kubernetes.io/service-account.name: "skywalking-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: spc-admin 
  namespace: spc 
  annotations:
    kubernetes.io/service-account.name: "spc-admin"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: uac-admin 
  namespace: uac  
  annotations:
    kubernetes.io/service-account.name: "uac-admin"
type: kubernetes.io/service-account-token
---
