- name: create sonarqube root dir
  file:
    path: '{{ sonar_dir }}'
    state: directory

- name: create sonarqube data dir
  file:
    path: '{{ sonar_dir }}/data'
    state: directory
    mode: '0777'

- name: create sonarqube postgresql dir
  file:
    path: '{{ sonar_dir }}/postgres'
    state: directory
    mode: '0777'

- name: cp docker-compose
  template:
    src: docker-compose.yml.j2
    dest: '{{ sonar_dir }}/docker-compose.yml'

- name: start sonarqube
  shell: docker compose up -d
  args:
   chdir: "{{ sonar_dir }}"

- name: wait sonarqube ready
  wait_for:
    port: 9000
    delay: 10
    timeout: 120
    msg: 'Timeout waiting for sonarqube respond'

