- name: modify limits
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - "root hard nproc 655360"
    - "root soft nproc 655360"
    - "root hard nofile 1048576"
    - "root soft nofile 1048576"

- name: modify sysctl
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - "fs.file-max = 1048576"
    - "net.core.somaxconn = 65535"
    - "net.ipv4.tcp_max_syn_backlog = 2048"
    - "vm.max_map_count = 655360"
    - "vm.swappiness = 1"
    - "net.ipv6.conf.all.disable_ipv6 = 1"
    - "net.ipv6.conf.default.disable_ipv6 = 1"
    - "net.ipv6.conf.lo.disable_ipv6 = 1"
    - "net.ipv4.tcp_mem = 786432 2097152 3145728"
    - "net.ipv4.tcp_rmem = 4096 4096 16777216"
    - "net.ipv4.tcp_wmem = 4096 4096 16777216"
    - "vm.min_free_kbytes = 61440"

- name: sysctl enable
  shell: sysctl -p /etc/sysctl.conf

#  Ubuntu不存在nf_conntrack
#  ubuntu没有iptables

- name: sysctl enable
  shell: sysctl -p

- name: 关闭ipv6自动配置
  lineinfile:
    path: /etc/netplan/01-netcfg.yaml
    regexp: "      dhcp6: yes"
    line: "      dhcp6: no"
- name: 添加network参数限制自动配置ipv4和ipv6
  lineinfile:
    path: /etc/netplan/01-netcfg.yaml
    line: "{{item}}"
  with_items:
    - "      accept-ra: no"
    - "      link-local: []"

- name: 禁止ssh连接参数UseDNS
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#UseDNS"
    line: "UseDNS no"
    state: present
- name: 重启sshd
  systemd:
    name: "sshd"
    state: restarted