- name: create kafka-exporter dir
  file:
    path: '{{ kafka_root_dir }}/kafka-exporter'
    state: directory
    mode: 0777

- name: check if kafka-exporter exists
  stat:
    path: '{{ kafka_root_dir }}/kafka-exporter/docker-compose.yml'
  register: kafka_compose_file

- name: stop existed kafka-exporter container
  shell: docker compose -f {{ kafka_root_dir }}/kafka-exporter/docker-compose.yml down
  when: kafka_compose_file.stat.exists == true
  args:
    chdir: "{{ kafka_root_dir }}/kafka-exporter"

- name: install kafka-exporter with docker compose
  template: 
    src: docker-compose.yml.j2
    dest: "{{ kafka_root_dir }}/kafka-exporter/docker-compose.yml"


- name: shutdown kafka-exporter
  command: docker compose -f {{ kafka_root_dir }}/kafka-exporter/docker-compose.yml down

- name: start up kafka-exporter
  command: docker compose -f {{ kafka_root_dir }}/kafka-exporter/docker-compose.yml up -d

- name: wait kafak-exporter ready
  wait_for:
    port: 9308
    timeout: 180
    msg: 'Timeout waiting for kafka-exporter respond'