---
- name: copy master join
  copy:
    src: /etc/ansible/k8s_join_shell/{{ groups['k8s_master_init'][0] }}/k8s_master_join.sh
    dest: "~/k8s_master_join.sh"

- name: master join shell
  shell: /bin/bash ~/k8s_master_join.sh

- name: add admin.conf
  shell: |
    mkdir -p $HOME/.kube
    cat /etc/kubernetes/admin.conf > $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: install kubelet completion bash
  lineinfile:
    path: ~/.bashrc
    line: 'source <(kubectl completion bash)'
