- name: print worker add
  shell: kubeadm token create --print-join-command
  register: k8s_worker_join

- name: show k8s_worker_add
  debug:
    msg: "{{ k8s_worker_join.stdout }}"

- name: create k8s_worker_join shell
  shell: |
    cat > k8s_worker_join.sh <<EOF
    {{ k8s_worker_join.stdout }}
    EOF

- name: copy k8s_worker_join to ansible hosts
  fetch: 
    src: k8s_worker_join.sh
    dest: /etc/ansible/k8s_join_shell/
