- name: 发送kubeadm配置文件
  template:
    src: kubeadm-config.yaml.j2
    dest: "/root/kubeadm-config.yaml"

- name: 清除节点原始数据
  shell: "/usr/bin/kubeadm reset -f"

- name: kubeadm初始化master节点
  shell: "/usr/bin/kubeadm init --config /root/kubeadm-config.yaml"
  register: result

- name: 显示执行结果
  debug:
    msg: "{{ result }}"

- name: 复制账户控制文件admin.conf
  shell: |
    mkdir -p $HOME/.kube
    cat /etc/kubernetes/admin.conf > $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: 生成加入master节点的证书certifcate_key
  shell: "/usr/bin/kubeadm init phase upload-certs --upload-certs --config /root/kubeadm-config.yaml | awk 'END {print}'"
  register: certifcate_key

- name: debug certifcate_key
  debug:
    var: certifcate_key

- name: 生成master加入集群的令牌
  shell: "kubeadm token create --print-join-command --certificate-key {{ certifcate_key.stdout }}"
  register: k8s_master_join

- name: 查看添加master令牌
  debug:
    msg: "{{ k8s_master_join.stdout }}"

- name: 创建master加入集群的shell脚本
  shell: |
    cat > k8s_master_join.sh <<EOF
    {{ k8s_master_join.stdout }}
    EOF

- name: 生成worker加入集群令牌
  shell: "/usr/bin/kubeadm token create --print-join-command"
  register: k8s_worker_join

- name: 查看添加worker令牌
  debug:
    msg: "{{ k8s_worker_join.stdout }}"

- name: 创建worker加入集群的shell脚本
  shell: |
    cat > k8s_worker_join.sh <<EOF
    {{ k8s_worker_join.stdout }}
    EOF

- name: 发送k8s_master_join脚本到ansible控制机
  fetch:
    src: k8s_master_join.sh
    dest: "/etc/ansible/k8s_join_shell/"

- name: 发送k8s_worker_join脚本到ansible控制机
  fetch: 
    src: k8s_worker_join.sh
    dest: "/etc/ansible/k8s_join_shell/"

- name: 安装自动补全
  shell: echo 'source <(kubectl completion bash)' >> ~/.bashrc

- name: 生效 ~/.bashrc
  shell: /bin/bash ~/.bashrc
