apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.25.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 10m
      smtp_require_tls: false
      smtp_smarthost: '{{ alertmanager_smtp_server }}'
      smtp_from: '{{ alertmanager_smtp_from }}'
      smtp_auth_username: '{{ alertmanager_smtp_username }}'
      smtp_auth_password: '{{ alertmanager_smtp_password }}'
    inhibit_rules:
      - source_match:
          alertname: BlackboxProbeFailed
        target_match_re:
          alertname: (BlackboxProbeHttpFailure|BlackboxSlowProbe|BlackboxProbeSlowHttp|BlackboxProbeSlowPing)
        equal: [ 'instance' ]
      - source_match_re:
          alertname: (KubeNodeNotReady|KubeNodeUnreachable)
        target_match_re:
          alertname: .*
        equal: [ 'node' ]
      - source_match_re:
          alertname: (KubeNodeNotReady|KubeNodeUnreachable)
        target_match_re:
          alertname: .*
        equal: [ 'nodename' ]
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: [ 'alertname', 'instance', 'service' ]
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'critical'
        equal: [ 'alertname', 'instance', 'service' ]
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'critical'
        equal: [ 'alertname', 'pod', 'job' ]
      - source_match:
          severity: 'warning'
        target_match:
          severity: 'warning'
        equal: [ 'alertname', 'pod', 'job' ]
      - source_match:
          severity: 'warning'
        target_match:
          severity: 'warning'
        equal: [ 'alertname', 'instance', 'job' ]
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'critical'
        equal: [ 'alertname', 'instance', 'job' ]
    route:
      group_by:
        - alertname
        - maintainer
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: it_owner
      routes:
        - receiver: 'webhook_gauss'
          group_by: [ 'category','DbIpAndPort' ]
          group_wait: 20s
          group_interval: 5m
          repeat_interval: 24h
          match_re:
            category: gs.*
        - receiver: 'app_owner'
          group_by: [ 'alertname','maintainer' ]
          group_wait: 20s
          group_interval: 5m
          repeat_interval: 24h
          match:
            alert_to: app_owner
    receivers:
      - name: it_owner
        email_configs:
          - to: "{{ alertmanager_app_email_to }}"
            send_resolved: true
      - name: app_owner
        email_configs:
          - to: "{{ "{{ .GroupLabels.maintainer }}" }}"
            send_resolved: true
      - name: 'webhook_gauss'
        webhook_configs:
          - url: 'http://gaussdb{{ domain_suffix }}.{{ domain_base }}/monitor-server/api/v1/sendGroupMail'
            send_resolved: false
type: Opaque
