- name: modify sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - "vm.overcommit_memory = 1"

- name: sysctl enable
  shell: sysctl -p /etc/sysctl.conf

- name: create root dir
  file:
    path: '{{ kafka_root_dir }}'
    state: directory
    mode: 0777

- name: check if kafka exists
  stat:
    path: '{{ kafka_root_dir }}/docker-compose.yml'
  register: kafka_compose_file

- name: stop existed kafka container
  shell: docker compose down
  when: kafka_compose_file.stat.exists == true
  args:
    chdir: "{{ kafka_root_dir }}"

- name: install with docker compose
  template: 
    src: docker-compose.yml.j2
    dest: "{{ kafka_root_dir }}/docker-compose.yml"

#- name: copy jmx-exporter files
#  synchronize:
#    src: files/
#    dest: '{{ kafka_root_dir }}'

- name: create jmx-exporter dir
  file:
    path: "{{ kafka_root_dir }}/jmx-exporter"
    state: directory

- name: copy jms-exporter file to kafka server
  copy:
    src: "{{ item }}"
    dest: "{{ kafka_root_dir }}/jmx-exporter/"
  with_items:
    - "files/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar"
    - "files/jmx-exporter/kafka-broker.yml"
    - "files/jmx-exporter/kafka_jmx_jvm_dashboard.json"

- name: shutdown kafka
  command: docker compose -f {{ kafka_root_dir }}/docker-compose.yml down

- name: start up kafka
  command: docker compose -f {{ kafka_root_dir }}/docker-compose.yml up -d

- name: wait kafak ready
  wait_for:
    port: 9092
    timeout: 180
    msg: 'Timeout waiting for kafka respond'