apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: podrestart-rules
  namespace: monitoring
spec:
  groups:
    - name: Prometheus-podRestart-rules
      rules:
        - alert: Infra-Pod重启
          expr: round(increase(kube_pod_container_status_restarts_total{namespace!~".*-apc.*",namespace!~".*-fdc-.*",namespace!~".*-rtd-.*",namespace!~".*-sdr-.*",namespace!~".*-yes-.*"}[5m])) > 0
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }} 发生重启，请应用协助查看具体原因"