apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: rocketmq-rules
  namespace: monitoring
spec:
  groups:
    - name: prometheus-rocketmq-rules
      rules:
        - alert: Infra-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic!~".*MES.*", topic!~".*ams.*", topic!~".*AMS.*", topic!~".*spc.*", topic!~".*APC.*", topic!~".*SDR.*", topic!~".*NOTICE.*", topic!~".*notice.*", topic!~".*REPORT.*"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Denny.Mou@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10000, VALUE={{$value}}"
        - alert: MES-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic=~".*MES.*", topic!~".*MESSAGE.*", topic!="MES_TASK_TASK_CHANGED_PROD"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Mark.Zhao@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: APC-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic=~".*APC.*"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Eric.Xu@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: SPC-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic=~".*spc.*"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Mark.Zhao@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: AMS-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic=~".*AMS.*"}/1000 > 10 or rocketmq_group_get_latency_by_storetime{topic=~".*ams.*"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Mark.Zhao@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: SDR-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic=~".*SDR.*"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Yu.Liao@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: Notice-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic=~".*NOTICE.*"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Mark.Zhao@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: Report-consumer消费延迟告警
          expr: 'rocketmq_group_get_latency_by_storetime{topic=~".*REPORT.*"}/1000 > 10'
          for: 3m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Mark.Zhao@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: ALL-rocketmq消息积压告警
          expr: sum(rocketmq_group_diff)by (group,topic) > 1000
          for: 5s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "leno.leno@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "消费组{{$labels.group}}消费{{$labels.topic}}的消息时出现消息积压, 积压量大于1000"
        - alert: ALL-rocketmq消息激增告警
          expr: sum(rocketmq_broker_tps{cluster="CimCluster"} - rocketmq_broker_tps{cluster="CimCluster"} offset 30s) by (cluster) > 5000
          for: 1s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "leno.leno@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "{{$labels.Cluster}}集群, 发送tps在过去30s内tps激增，增量超过5000"
        - alert: MQ-broker压力大告警
          expr: sum(rocketmq_broker_tps{cluster="CimCluster"} - rocketmq_broker_tps{cluster="CimCluster"} offset 30s) by (cluster) > 5000
          for: 1m
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "leno.leno@sienidm.com"
            #邮件抄送人
            mail_cc: "Rainy.Liu@sienidm.com,Denny.Mou@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "broker: {{$labels.brokerIP}}, 消息等待处理时间已经超过200ms"