apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-gauss-rules
  namespace: monitoring
spec:
  groups:
    - name: prometheus-gauss-rules
      rules:
        - alert: Gauss Alarm.log新增告警
          expr: gauss_alarm == 0
          for: 1s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
        - alert: Gauss出现死锁告警
          expr: gauss_trc == 0
          for: 1s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
        - alert: Gauss逻辑复制日志告警
          expr: gauss_logicrep == 0
          for: 1s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
        - alert: Gauss集群状态异常告警
          expr: gauss_cluster_status_check > 0
          for: 5s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.alert_db }}集群状态异常:{{ $labels.description }}"
        - alert: Gauss Gs_Check_10m告警
          expr: gs_check_item_10m > 0
          for: 5s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
        - alert: Gauss Gs_Check_24h告警
          expr: gs_check_item_24h > 0
          for: 5s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
        - alert: Gauss物理复制不同步告警
          expr: gauss_physics_copy_alert > 0
          for: 1s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
            sql: "{{ $labels.sql }}"
            sql_result: "{{ $labels.sql_result }}"
        - alert: Gauss LongSQL告警
          expr: gauss_longsql_alert > 0
          for: 1s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
            sql: "{{ $labels.sql }}"
            sql_result: "{{ $labels.sql_result }}"
        - alert: Gauss LongTrans告警
          expr: gauss_longtrans_alert > 0
          for: 1s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
            sql: "{{ $labels.sql }}"
            sql_result: "{{ $labels.sql_result }}"
        - alert: Gauss Dv_sessions告警
          expr: gauss_sessions_connet_alert > 3200
          for: 1s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
            sql: "{{ $labels.sql }}"
            sql_result: "{{ $labels.sql_result }}"
        - alert: Gauss SYS_sessions告警
          expr: gauss_sessions_sys_connet_alert > 8
          for: 1s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
            sql: "{{ $labels.sql }}"
            sql_result: "{{ $labels.sql_result }}"
        - alert: Gauss Dc_pool使用率告警
          expr: gauss_dc_pool_alert_val > 70
          for: 1s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.alert_db }}{{$labels.description}},value={{ $value }}%"
        - alert: Gauss Dc_pool增长率告警
          expr: delta(gauss_dc_pool_alert_val[5m]) > 10
          for: 2s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.alert_db }} DC_POOL 5分钟内增长率超过10%,value={{ $value }}%"
        - alert: Gauss数据库表空间使用率超过85%告警
          expr: gauss_tablespace_used_alert > 0
          for: 5s
          labels:
            severity: critical
            msg_rate: send_24h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
            sql: "{{ $labels.sql }}"
            sql_result: "{{ $labels.sql_result }}"