apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: rocketmq-rules
  namespace: monitoring
spec:
  groups:
    - name: prometheus-rocketmq-rules
      rules:
        - alert: FDC-consumer消费延迟告警
          expr: rocketmq_group_get_latency_by_storetime/1000 > 10
          for: 3m
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "IT-CIM-FABC-FDC-PROD@sienidm.com"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "FAB-C环境consumer={{$labels.group}}消费延迟超过10s, VALUE={{$value}}"
        - alert: FDC-topic消费延迟告警
          expr: (sum by(topic) (rocketmq_producer_offset{topic=~"FDC_PRODC_.*"}) - on(topic) group_right() sum by(group, topic) (rocketmq_consumer_offset{topic=~"FDC_PRODC_.*"})) - ignoring(group) group_left() sum by(topic) (avg_over_time(rocketmq_producer_tps{topic=~"FDC_PRODC_.*"}[5m])) * 5 * 60 > 1000
          for: 10m
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "IT-CIM-FABC-FDC-PROD@sienidm.com"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "FAB-C环境consumer={{$labels.group}},topic={{$labels.topic}}消费延迟，延迟量{{$value}}"