apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-infra-rules
  namespace: monitoring
spec:
  groups:
    - name: prometheus-infra-rules
      rules:
        - alert: Infra-App_full_gc增量告警
          expr: sum(app_full_gc_check) by(pod_name,name_space) - sum(app_full_gc_check offset 1d) by(pod_name,name_space) > 1
          for: 5s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Rainy.Liu@sienidm.com"
            #邮件抄送人
            mail_cc: "Denny.Mou@sienidm.com,leno.leno@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "ns={{ $labels.name_space }}, pod={{ $labels.pod_name }}, 24小时内fall_gc增量为：{{ $value }}"
        - alert: Infra-POD-CPU使用率超高告警
          expr: sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate)by(pod)/sum(kube_pod_container_resource_limits_cpu_cores)by(pod) * 100 > 50
          for: 5m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Rainy.Liu@sienidm.com"
            #邮件抄送人
            mail_cc: "Denny.Mou@sienidm.com,leno.leno@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }}在过去5分钟CPU使用率持续超过50%"
        - alert: Infra-POD内存使用率超高告警（非JAVA应用）
          expr: sum(container_memory_working_set_bytes{container!=""})by(namespace,pod,maintainer)/sum(kube_pod_container_resource_limits_memory_bytes)by(namespace,pod,maintainer) * 100 > 80
          for: 1m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "Rainy.Liu@sienidm.com"
            #邮件抄送人
            mail_cc: "Denny.Mou@sienidm.com,leno.leno@sienidm.com"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }}内存使用率超过80%"