apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-rtd-rules
  namespace: monitoring
spec:
  groups:
    - name: prometheus-rtd-rules
      rules:
        - alert: RTD-数据库总连接超高warning
          expr: 65 < (hikaricp_connections{namespace=~".*-rtd-.*"} / hikaricp_connections_max{namespace=~".*-rtd-.*"} * 100) <= 80
          for: 1m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }} 当前(hikaricp_connections/hikaricp_connections_max)*100={{ $value }}%"
        - alert: RTD-数据库总连接超高critical
          expr: (hikaricp_connections{namespace=~".*-rtd-.*"} / hikaricp_connections_max{namespace=~".*-rtd-.*"} * 100) > 80
          for: 1m
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }} 当前(hikaricp_connections/hikaricp_connections_max)*100={{ $value }}%"
        - alert: RTD-数据库等待连接超高
          expr: hikaricp_connections_pending{namespace=~".*-rtd-.*"} > 10
          for: 1m
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }} 当前等待连接数：{{ $value }}"
        - alert: RTD-数据库连接创建超时
          expr: increase(hikaricp_connections_timeout_total{namespace=~".*-rtd-.*"}[720m]) > 10
          for: 1m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }} 当前创建超时的连接数：{{ $value }}"
        - alert: RTD-POD重启
          expr: round(increase(kube_pod_container_status_restarts_total{namespace=~".*-rtd.*"}[5m])) > 0
          for: 5s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }} 发生重启"
        - alert: RTD-Blackbox-http探测失败告警
          expr: probe_success{job="blackbox-http",namespace=~".*-rtd.*"} == 0
          for: 10s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }} 探测失败"
        - alert: RTD-容器内线程数超高告警
          expr: container_threads{namespace=~".*-rtd.*"} > 2000
          for: 10s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.pod }}容器内线程数超过阈值2000"
        - alert: RTD-表空间使用率告警
          #fixme gaussDB 需要修改IP
          expr: gauss_tablespace_used_pct{alert_db="10.13.171.151"} > 80
          for: 10s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "{{ $labels.description }}"
        - alert: RTD-JVM使用率告警Warning
          expr: 80 < sum(jvm_memory_used_bytes{namespace=~".*-rtd-.*"}) by (namespace, service, pod) / sum(jvm_memory_max_bytes{namespace=~".*-rtd-.*"}) by (namespace, service, pod) *100 < 90
          for: 10m
          labels:
            severity: warning
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "当前POD={{ $labels.pod }} JVM使用率超过80%"
        - alert: RTD-JVM使用率告警Critical
          expr: 90 <= sum(jvm_memory_used_bytes{namespace=~".*-rtd-.*"}) by (namespace, service, pod) / sum(jvm_memory_max_bytes{namespace=~".*-rtd-.*"}) by (namespace, service, pod) *100
          for: 10m
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #alarm_owner: ""
          annotations:
            description: "当前POD={{ $labels.pod }} JVM使用率超过90%"
        - alert: RTD-Kafka消费延迟超5000告警
          expr: kafka_consumergroup_lag{topic="RTD_G2G_DATA_SYNC_N"} > 5000
          for: 30s
          labels:
            severity: critical
            msg_rate: send_12h
            #邮件接收人
            mail_to: "EMAIL_TO"
            #邮件抄送人
            mail_cc: "EMAIL_CC"
            #短信接收人
            #phones: ""
            #welink接收人
            #workNo: ""
            #ITSM事件单
            #severity: "event_list"
            #alarm_owner: ""
          annotations:
            description: "consumergroup={{ $labels.consumergroup }},topic={{ $labels.topic }},RTD kafka消费延迟,value={{ $value }}"