- name: ensure directory structure exists
  file:
    path: '{{ syslog_manifest_dir }}'
    state: directory

- name: copy config templates to master
  template:
    src: '{{ item.src }}'
    dest: "{{ syslog_manifest_dir }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_filetree: templates/
  when: item.state == 'file'

- name: apply config yaml 
  command: kubectl apply -f {{ syslog_manifest_dir }}/rsyslog-logstash.yml